---  
instances:
    - server_name: front21
      configuration: standalone-ha.xml
      bind_addr : "{{ ansible_host }}"
      port_offset: 100
      MGMT_ADDR : "{{ ansible_host }}" # 127.0.0.1 
      java_heap_min: 1024m
      java_heap_max: 1024m
      java_perm_min: 128m
      java_perm_max: 1024m
      multicast_addr: "231.0.1.1"
      jm_multicast_addr: "232.0.1.1"
      mc_multicast_addr: "233.0.1.1" 
      jgroups-stack: udp
      jgroups-member:
        - addr: 192.168.56.202
          port: 7900 
        - addr: 192.168.56.203
          port: 7900 
        - addr: 192.168.56.203
          port: 7900  
    - server_name: front22
      configuration: standalone-ha.xml
      bind_addr : "{{ ansible_host }}"
      port_offset: 200
      MGMT_ADDR : "{{ ansible_host }}" # 127.0.0.1 
      java_heap_min: 1024m
      java_heap_max: 1024m
      java_perm_min: 128m
      java_perm_max: 1024m
      multicast_addr: "231.0.1.2"
      jm_multicast_addr: "232.0.1.2"
      mc_multicast_addr: "233.0.1.2" 
      jgroups-stack: tcp
      jgroups-member:
        - addr: 192.168.56.202
          port: 7900 
        - addr: 192.168.56.203
          port: 7900 
        - addr: 192.168.56.203
          port: 7900 